booking_app/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('customer.urls', namespace='customer')),
    path('api/', include('main.urls', namespace='main')),
    path('', include('owner.urls', namespace='owner')),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *


app_name = "main"

urlpatterns = [
    path("categories",category_api_view, name="category_api_view"),
    path("category/<int:pk>/services",category_detail_view, name="category_detail_view"),
    path("service/<int:pk>",service_detail_view, name="service_detail_view"),

]

owner/urls.py
from django.urls import path
from .views import *
from django.conf.urls import handler404,handler500

from django.views import static

app_name = 'owner'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', logout_, name='log_out'),
    path('profil', OwnerProfilView.as_view(), name='owner_profil'),
    path('intro', IntroView.as_view(), name='intro'),
    path('verification', VerificationView.as_view(), name='verification'),
    path('service' , ServiceView.as_view(),name = 'service'),
    path('service/<int:pk>' , ServiceDetailView.as_view(),name = 'service_detail'),
    path('room_create/<int:pk>' , RoomView.as_view(),name = 'room_create'),
    path('room/<int:pk>',RoomView.as_view(),name = 'room'),
    path('room/update/<int:pk>',RoomUpdateView.as_view(),name = 'room_update'),
    path('brons/<int:pk>',BronView.as_view(),name = 'brons'),
    path('calendar/<int:pk>',calendar_view,name = 'calendar'),
    path('add/bron/',BronAddView.as_view(),name = 'add_bron'),
    path('cancel/bron',BronCancelView.as_view(),name = 'cancel_bron'),
    path('infoBrons', InfoBrons.as_view(),name='info_brons'),
    path('updateBron/<int:pk>', CalendarUpdateBron.as_view(),name='update_bron'),
    path('get/room', get_room,name='get_room'),
    path('delete_room/<int:pk>/<int:id_service>' , DeleteRoomView.as_view() , name = "delete_room"),
    path('delete_image/<int:pk>/<int:id_room>' , DeleteImageView.as_view() , name= "delete_image" )
    
]

handler404=handler_404
handler500=handler_500

templates/bron_list.html
{% extends 'wrapper.html' %}


{% block content %}
<div class="main-panel">
    <div class="content-wrapper">

        <div class="card">
            {% for b in brons %}
            <div class="card-title">{{ b }}</div>
            {% endfor %}
        </div>

</div>
</div>


{% endblock %}

templates/intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/assets/boostrap/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/assets/boostrap/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/assets/boostrap/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="/static/assets/fonts/Ubuntu/Ubuntu-Regular.woff">
    <title>Introduction</title>
</head>
<body>
   <div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1 class="text" style="font-size: 55px; margin-top:25%; color: #3e4450;">Elegant and creative solutions</h1>
            <h3 class="text " style="font-family: 'Raleway', sans-serif; color: #858ea1;">Lorem ipsum W dolor sit amet consectetur adipisicing elit. Dicta sunt architecto aperiam tempora corporis maiores! </h3>
            <a href="{% url 'owner:login' %}" class="btn w-25 mt-4 p-2 m-1"><h5 class="text text-light card-title">Kirish</h5></a>
            <a href="" class="btn  w-30 mt-4 p-2 m-1"><h5 class="text text-light card-title">Ro'yxatdan o'tish</h5></a>
        </div>
        <div class="col-md-6">
          <img src="/static/assets/images/hero-img.png" class="img-fluid animated" alt="">
            
        </div>
    </div>
   </div>
</body>
<style>
    .btn{
        background: linear-gradient(to right,rgb(28, 221, 111) , rgb(93, 206, 146) , rgb(31, 223, 114)  );
    }
    .btn:hover{
        background: rgba(1, 109, 241, 0.835);
    }
</style>
</html>

templates/room_parametr.html
{% extends 'wrapper.html' %}


{% block li %}

<li class="nav-item">
  <a class="nav-link" href="{% url 'owner:brons' room.service.id %}">
    <span class="menu-title">Taqvim</span>
    <i class="mdi mdi-calendar menu-icon"></i>
  </a>
</li> 
{% endblock  %}

{% block content %}

<!-- Example -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div class="main-panel p-5 ">

<!-- <div class="container "> -->
  
  <div class="row " >

   <!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Xonani ochirish.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-dal-content">
           
            <div class="modhidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Xonani ochirishdi xoxlaysizmi ?
      </div>
      <div class="modal-footer">

        <a href="{% url 'owner:delete_room' room.id room.service.id %}" style="text-decoration: none;"> <button type="button" class="btn btn-danger  me-2" data-toggle="modal">
          Xa 
        </button></a>
        <button type="button" class="btn btn-primary  close" data-dismiss="modal" aria-label="Close"> Yoq</button>

      </div>
    </div>
  </div>
</div>


     <div class="col-md-6 ">
      <div class="card">

    
        <div id="CarouselTest" class="carousel slide " data-ride="carousel">

          <!-- <ol class="carousel-indicators">
            <li data-target="#CarouselTest" data-slide-to="0" class="active"></li>
            <li data-target="#CarouselTest" data-slide-to="1"></li>
            <li data-target="#CarouselTest" data-slide-to="2"></li>
          </ol> -->

          <div class="carousel-inner">
            {% for i in room.room_photos.all %}
            
            {% if forloop.first %}
            <div class="carousel-item active">
            {% else %}
            <div class="carousel-item">
            {% endif %}
            <div class="" style="width: 450px; height: 100%;">
              <!-- <button type="button"  data-toggle="modal" data-target="#exampleModal2" class="btn btn mdi mdi-delete text-danger"  style="font-size: 24px; position:absolute; right:20px; top:20px; background:rgba(0, 0, 0, 0.5); padding:5px; border-radius:5px;">fjuuuuu</button> -->
              <img class="d-block" src="{{ i.image.url }}" width="100%" height="100%" alt="">
              <!-- <a href="{{i.image.url}}">              </a> -->
          
             <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Xonani ochirish.</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-dal-content">
                       
                        <div class="modhidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Shu rasmni ochirishdi xoxlaysizmi ?
                  </div>
                  <div class="modal-footer">
                    <img src="{{i.image.url}}" alt="" width="100%" height="100%">
                    <a href="{% url 'owner:delete_image' i.id  room.id%}">  <button type="button" class="btn btn-danger  me-2" data-toggle="modal">
                      Xa 
                    </button></a>
                    <button type="button" class="btn btn-primary  close" data-dismiss="modal" aria-label="Close"> Yoq</button>
            
                  </div>
                </div>
              </div>
            </div>
            </div>
            </div>
            
            {% endfor %}
            
            <a class="carousel-control-prev" href="#CarouselTest" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only"></span>
            </a>
            <a class="carousel-control-next" href="#CarouselTest" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only"></span>
          </a>
          </div>
        </div>
        </div>

          <div class="card">
            <div class="card-body">
              <form action="" method="post" class="form mb-5" enctype='multipart/form-data'>{% csrf_token %}
                <input type='file' id="getFile" name="image" >
                <button type="submit" class="btn btn-gradient-info  mt-2 ml-5">Yuklash <i class="icon-lg mdi mdi-upload"></i></button>
            <button type="button" class="btn btn-gradient-danger  mt-2" data-toggle="modal" data-target="#exampleModal2" style="margin-left:10px;">Rasmni o'chirish<i class="icon-lg mdi mdi-delete" ></i></button>
                
              </form>
             
              <form class="forms-sample" method="post" action="">
                {% csrf_token %}
                <div class="form-group row">
                  <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Xona nomi</label>
                  <div class="col-sm-9">
                    <input type="text" value="{{ room.name }}" class="form-control" name="name" id="exampleInputUsername2" placeholder="Xona nomi (1-xona)">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Xona egasi</label>
                  <div class="col-sm-9">
                    <input type="text" value="{{ room.owner }}" class="form-control" name="owner" id="exampleInputEmail2" placeholder="Xona egasi">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="exampleInputMobile" class="col-sm-3 col-form-label">Manzil</label>
                  <div class="col-sm-9">
                    <input type="text" value="{{ room.adres }}" class="form-control" name="adres" id="exampleInputMobile" placeholder="Manzil">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="exampleInputPassword2" class="col-sm-3 col-form-label">O'lchami </label>
                  <div class="col-sm-9">
                    <input type="text" value="{{ room.size }}" class="form-control" name="size" id="exampleInputPassword2" placeholder="O'lchami">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="exampleInputConfirmPassword2" class="col-sm-3 col-form-label">Xona haqida</label>
                  <div class="col-sm-9">
                    <textarea name="description" id="" class="form-control" cols="30" rows="4">{{ room.description }}</textarea>
                  </div>
                </div>
              
                <button type="submit" class="btn btn-gradient-primary me-2 mdi mdi-settings me-2" style="margin-left: 200px;">O'zgartirish</button>

             
                
              </form>

            </div>
      </div>
    </div>
    
    <div class="col-md-6 ">
      <div class="card">
        <div class="card-body">
          <div class="card-text">{{ room.name }} ni band qilish</div>
          <form action="{% url 'owner:add_bron' %}" method="post" class="form mt-3 p-3">
            {% csrf_token %}
            <div class="form-group row d-none">
              <label for="" class="col-sm-3 col-form-label">Kimning nomiga</label>
              <div class="col-sm-9">
                <input type="text" value="{{ room.id }}"  class="form-control" name="room_" id="exampleInputMobile" placeholder="Ism">
              </div>
            </div>
            <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Kimning nomiga</label>
              <div class="col-sm-9">
                <input type="text"  class="form-control" name="name" id="exampleInputMobile" placeholder="Ism">
              </div>
            </div>
            <div class="form-group row">
              <label for="exampleInputMobile" class="col-sm-3 col-form-label">Telefon raqam</label>
              <div class="col-sm-9">
                <input type="text"  class="form-control" name="phone" id="exampleInputMobile" placeholder="Telefon">
              </div>
            </div>
            <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <label for="date_"> <h5>Sanani tanlang</h5></label>
                  <input type="date" id="date_" class="form-control form-control-lg" name="date" required>
                </div>
              </div>

              <div class="col-md-4">
                <div class="form-group">
                  <label for="timefrom"> <h5>00:00 dan  </h5></label>
                  <input type="time" id="timefrom" class="form-control form-control-lg" name="bron_time_from" required>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label for="timeto"> <h5>00:00 gacha</h5></label>
                  <input type="time" id="timeto" class="form-control form-control-lg" name="bron_time_to"  required>
                </div>
              </div>
              
            </div>
            <div class="text-left">
              <button type="submit" class="btn btn-gradient-warning ">Bron qilish</button>
            </div>


          </form>

        </div>

            </div>
            <button type="button" class="btn btn-gradient-danger mdi mdi-delete me-2" data-toggle="modal" data-target="#exampleModal" style = "margin-top: 370px; margin-left:200px; font-size: larger;">
              Xonani ochirish
               </button>
        </div>
        
        </div>
      </div>
      
    </div>




  </div>
  </div>
  
  <!-- End of card -->

 




<style>
  body {
  background-color:  #eee;
}

.carousel-indicators li {
    border-radius: 12px;
    width: 12px;
    height: 12px;
    background-color: #404040;
}
.carousel-indicators li {
    border-radius: 12px;
    width: 12px;
    height: 12px;
    background-color: #404040;
}
.carousel-indicators .active {
    background-color: white;
    max-width: 12px;
    margin: 0 3px;
    height: 12px;
}
.carousel-control-prev-icon {
 background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
}

.carousel-control-next-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important;
}


.btn {
  margin-top: auto;
}
</style>

{% endblock %}

templates/wrapper.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/static/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/static/assets/boostrap/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/boostrap/bootstrap/css/bootstrap.css">
     <link rel="stylesheet" href="/static/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="/static/assets/images/favicon.ico" />
  </head>
  <body>
    <div class="container-scroller">
     
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href="index.html"><img src="/static/assets/images/logo.svg" alt="logo" /></a>
          <a class="navbar-brand brand-logo-mini" href="index.html"><img src="/static/assets/images/logo-mini.svg" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button> 
        
          <ul class="navbar-nav navbar-nav-right">
            
            <li class="nav-item d-none d-lg-block full-screen-link">
              <a class="nav-link">
                <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-email-outline"></i>
                <span class="count-symbol bg-warning"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                <h6 class="p-3 mb-0">Messages</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="/static/assets/images/faces/face4.jpg" alt="image" class="profile-pic">
                  </div>
                  <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                    <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
                    <p class="text-gray mb-0"> 1 Minutes ago </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="/static/assets/images/faces/face2.jpg" alt="image" class="profile-pic">
                  </div>
                  <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                    <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
                    <p class="text-gray mb-0"> 15 Minutes ago </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="/static/assets/images/faces/face3.jpg" alt="image" class="profile-pic">
                  </div>
                  <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                    <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
                    <p class="text-gray mb-0"> 18 Minutes ago </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <h6 class="p-3 mb-0 text-center">4 new messages</h6>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
                <i class="mdi mdi-bell-outline"></i>
                <span class="count-symbol bg-danger"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                <h6 class="p-3 mb-0">Notifications</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-success">
                      <i class="mdi mdi-calendar"></i>
                    </div>
                  </div>
                  <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                    <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
                    <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-warning">
                      <i class="mdi mdi-settings"></i>
                    </div>
                  </div>
                  <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                    <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
                    <p class="text-gray ellipsis mb-0"> Update dashboard </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-info">
                      <i class="mdi mdi-link-variant"></i>
                    </div>
                  </div>
                  <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                    <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
                    <p class="text-gray ellipsis mb-0"> New admin wow! </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <h6 class="p-3 mb-0 text-center">See all notifications</h6>
              </div>
            </li>
            <li class="nav-item nav-logout d-none d-lg-block">
              <a class="nav-link" href="{% url 'owner:log_out' %}">
                
                <i class="mdi mdi-power"></i>
              </a>
              
            </li>
            <li class="nav-item nav-settings d-none d-lg-block">
              <a class="nav-link" href="#">
                <i class="mdi mdi-format-line-spacing"></i>
              </a>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas " id="sidebar">
          <ul class="nav">
            <li class="nav-item nav-profile">
              <a href="{% url 'owner:owner_profil' %}" class="nav-link">
                <div class="nav-profile-image">
                  <img src="/static/assets/images/faces/face1.jpg" alt="profile">
                  <span class="login-status online"></span>
                  <!--change to offline or busy as needed-->
                </div>
                <div  class="nav-profile-text d-flex flex-column">
                  <span class="font-weight-bold mb-2">{{ request.user.first_name }} {{ request.user.last_name }} </span>
                  <span class="text-secondary text-small">CEO <i class=" mdi mdi-check-circle text-primary nav-profile-badge"></i></span>
                </div>
                
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'owner:home' %}">
                <span class="menu-title">Mening bizneslarim</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href=>
                <span class="menu-title">Bron qilinganlar</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="index.html">
                <span class="menu-title">Umumiy reyting</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'owner:add_bron' %}">
                <span class="menu-title">Bron qilish</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
            
            {% block li %}
            
            {% endblock  %}
           
           
          </ul>
        </nav>


        {% block content %}
        {% endblock content %}
        
      
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            
            {% if message.tags == 'success' %}
            
              <div class="text-center alert alert-success alert-dismissible fade show msg" role="alert" >
                <i class="bi bi-check-circle me-1"></i>
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% elif message.tags == 'error' %}
              <div class="text-center alert alert-danger alert-dismissible fade show msg" role="alert "   >
                <i class="bi bi-x-circle me-1"></i>
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            
            {% else %}
            {% endif %}
      
            {% endfor %}
        </ul>
        {% else %}
      {% endif %}

      <style>
        .msg{
           position: fixed;
           right: 0;
           bottom: 50px;
           width: 25%;
           animation: run 1s linear ;
           z-index: 100;
          
         }
         @keyframes run {
         from{ 
             transform: translateX(500px);   
         }
         to{
             transform: translateX(-8px);   
         }
   }
       
     </style>
      

         <!-- <footer class="footer">
            <div class="container-fluid d-flex justify-content-center">
              <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © Future coders 2023</span>
            </div>
          </footer> -->
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <!-- <script src="/static/assets/vendors/js/vendor.bundle.base.js"></script> -->
    <script src="/static/calendar/assets/js/bundle/bootstrap.bundle.js"></script>
   
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="/static/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="/static/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/static/assets/js/off-canvas.js"></script>
    <script src="/static/assets/js/hoverable-collapse.js"></script>
    <script src="/static/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="/static/assets/js/dashboard.js"></script>
    <script src="/static/assets/js/todolist.js"></script>
    <!-- End custom js for this page -->
  </body>
</html>